1.7.0

diff --git a/scripts/genericLinuxBuildQt4 b/scripts/genericLinuxBuildQt4
--- a/scripts/genericLinuxBuildQt4
+++ b/scripts/genericLinuxBuildQt4
@@ -1,14 +1,29 @@
 #!/bin/bash
 
 QMAKE=qmake-qt4
+if ! which $QMAKE; then
+    echo "$QMAKE not found."
+    exit -1
+fi
+
 TAR=tar
+if ! which $TAR; then
+    echo "$TAR not found."
+    exit -1
+fi
+
 LRELEASE=lrelease
+if ! which $LRELEASE; then
+    echo "$LRELEASE not found."
+    exit -1
+fi
+
 NUM_CPUS=$(cat /proc/cpuinfo | grep processor | wc -l)
 
 # Package naming
 
 NAME=dustrac
-VERSION=1.6.3
+VERSION=${DUSTRAC_RELEASE_VERSION?"is not set."}
 ARCH=linux-x86_64
 QT=qt4
 
diff --git a/scripts/genericLinuxBuildQt5 b/scripts/genericLinuxBuildQt5
--- a/scripts/genericLinuxBuildQt5
+++ b/scripts/genericLinuxBuildQt5
@@ -3,14 +3,29 @@
 # Assumes, that you have installed (static) qt5 to ~/qt5.
 
 QT5_QMAKE=~/qt5/bin/qmake
+if ! which $QT5_QMAKE; then
+    echo "$QT5_QMAKE not found."
+    exit -1
+fi
+
 TAR=tar
+if ! which $TAR; then
+    echo "$TAR not found."
+    exit -1
+fi
+
 LRELEASE=lrelease
+if ! which $LRELEASE; then
+    echo "$LRELEASE not found."
+    exit -1
+fi
+
 NUM_CPUS=$(cat /proc/cpuinfo | grep processor | wc -l)
 
 # Package naming
 
 NAME=dustrac
-VERSION=1.6.3
+VERSION=${DUSTRAC_RELEASE_VERSION?"is not set."}
 ARCH=linux-x86_64
 QT=qt5
 
diff --git a/scripts/mxeWindowsBuild b/scripts/mxeWindowsBuild
--- a/scripts/mxeWindowsBuild
+++ b/scripts/mxeWindowsBuild
@@ -3,16 +3,37 @@
 # Assumes, that you have installed qt5, libopenal and libvorbisfile via MXE.
 
 MXE_QT5_QMAKE=~/mxe/usr/i686-pc-mingw32/qt5/bin/qmake
+
 ZIP=zip
+if ! which $ZIP; then
+    echo "$ZIP not found."
+    exit -1
+fi
+
 UNIX2DOS=unix2dos
+if ! which $UNIX2DOS; then
+    echo "$UNIX2DOS not found."
+    exit -1
+fi
+
 MAKENSIS=makensis
+if ! which $MAKENSIS; then
+    echo "$MAKENSIS not found."
+    exit -1
+fi
+
 LRELEASE=lrelease
+if ! which $LRELEASE; then
+    echo "$LRELEASE not found."
+    exit -1
+fi
+
 NUM_CPUS=$(cat /proc/cpuinfo | grep processor | wc -l)
 
 # Package naming
 
 NAME=dustrac
-VERSION=1.6.3
+VERSION=${DUSTRAC_RELEASE_VERSION?"is not set."}
 ARCH=windows-x86
 QT=qt5
 
